version: '3.7'
services:
  # ===============================================
  # PHP-FPMの設定（PHPの設定）
  # ===============================================
  nlap:
    image: 'centos:8'
    ports:
      - 8080:80
    links:
      - nldb
    depends_on:
      - nldb
  # ===============================================
  # MySQLの設定
  # ===============================================
  nldb:
    image: 'mysql'
    ports:
      - "3306:3306"
    user: "1000:50"
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      # このDBはmysql内でデフォルトで作成され
      # rootと一般ユーザ( `MYSQL_USER` )がグローバル権限を持ってる
      MYSQL_DATABASE: nomilog